package ai.kilocode.client.session

import com.intellij.testFramework.fixtures.BasePlatformTestCase
import com.intellij.ui.AnimatedIcon
import com.intellij.util.ui.JBUI
import java.awt.image.BufferedImage
import javax.swing.Icon

/**
 * Parity fixtures generated by running the actual web implementation
 * (`packages/kilo-ui/src/components/agent-avatar-identity.ts`) against representative ids, so this
 * port is checked against real output rather than against a re-derivation of the same algorithm.
 * Regenerate with `bun run <script importing identity()/palette()>` if the web algorithm changes.
 */
class AgentAvatarTest : BasePlatformTestCase() {

    fun `test identity matches the web implementation for representative ids`() {
        assertIdentity("ses_aaa", 6, setOf(1, 2, 3, 5, 7, 9, 10, 12, 14, 15, 16, 17, 18, 19))
        assertIdentity("ses_bbb", 0, setOf(2, 7, 12, 15, 16, 17, 18, 19))
        assertIdentity("ses_child", 1, setOf(6, 8, 11, 12, 13, 17, 21, 22, 23))
        assertIdentity("ses_one", 3, setOf(1, 2, 3, 5, 6, 8, 9, 11, 13, 16, 18, 21, 22, 23))
        assertIdentity("a", 1, setOf(1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 18))
        assertIdentity("ses_x1", 2, setOf(2, 6, 7, 8, 10, 11, 13, 14, 16, 18, 21, 23))
        assertIdentity("ses_x2", 6, setOf(12, 15, 16, 17, 18, 19, 21, 22, 23))
        assertIdentity("ses_x3", 7, setOf(2, 6, 7, 8, 10, 11, 12, 13, 14, 17, 21, 22, 23))
    }

    fun `test unknown and blank ids share the same neutral identity as the web implementation`() {
        val neutral = setOf(6, 8, 11, 13, 16, 18, 21, 23)
        assertIdentity("unknown", null, neutral)
        assertIdentity("", null, neutral)
    }

    fun `test identity is deterministic for the same id`() {
        val first = AgentAvatarIdentity.identity("ses_repeat")
        val second = AgentAvatarIdentity.identity("ses_repeat")

        assertEquals(first, second)
    }

    fun `test different ids usually produce different cell shapes`() {
        val a = AgentAvatarIdentity.identity("ses_aaa")
        val b = AgentAvatarIdentity.identity("ses_bbb")

        assertFalse(a.cells == b.cells)
    }

    fun `test known identities never light a grid corner`() {
        for (id in listOf("ses_aaa", "ses_bbb", "ses_child", "ses_one", "a", "ses_x1", "ses_x2", "ses_x3")) {
            val cells = AgentAvatarIdentity.identity(id).cells
            assertTrue("$id touches a corner", cells.none { it in setOf(0, 4, 20, 24) })
        }
    }

    fun `test palette matches the web implementation for nine spawn-order siblings`() {
        val ids = listOf("ses_aaa", "ses_bbb", "ses_ccc", "ses_ddd", "ses_eee", "ses_fff", "ses_ggg", "ses_hhh", "ses_iii")

        val palette = AgentAvatarIdentity.palette(ids)

        assertEquals(
            mapOf(
                "ses_aaa" to 6,
                "ses_bbb" to 0,
                "ses_ccc" to 7,
                "ses_ddd" to 4,
                "ses_eee" to 1,
                "ses_fff" to 5,
                "ses_ggg" to 2,
                "ses_hhh" to 3,
                "ses_iii" to 5,
            ),
            palette,
        )
    }

    fun `test palette keeps the first eight siblings distinct`() {
        val ids = (1..8).map { "ses_$it" }

        val colors = AgentAvatarIdentity.palette(ids).values

        assertEquals(8, colors.toSet().size)
    }

    fun `test palette repeats colors only after eight siblings, ninth reuses`() {
        val ids = (1..9).map { "ses_$it" }

        val palette = AgentAvatarIdentity.palette(ids)

        assertEquals(9, palette.size)
        assertEquals(8, palette.values.toList().dropLast(1).toSet().size)
    }

    fun `test static avatar is not animated and running avatar is`() {
        val static = AgentAvatar.static("ses_static")
        val running = AgentAvatar.running("ses_static")

        assertFalse(static is AnimatedIcon)
        assertTrue(running is AnimatedIcon)
    }

    fun `test static and running avatars report the same fixed dimensions`() {
        val static = AgentAvatar.static("ses_dims")
        val running = AgentAvatar.running("ses_dims")

        assertEquals(JBUI.scale(16), static.iconWidth)
        assertEquals(JBUI.scale(16), static.iconHeight)
        assertEquals(static.iconWidth, running.iconWidth)
        assertEquals(static.iconHeight, running.iconHeight)
    }

    fun `test a supplied color overrides the identity's hashed hue`() {
        // `ses_child` has preferred hue 1 in the parity fixture above, so slot 3 must repaint it.
        val hashed = AgentAvatar.static("ses_child")
        val overridden = AgentAvatar.static("ses_child", color = 3)

        assertFalse(pixels(hashed).contentEquals(pixels(overridden)))
    }

    private fun assertIdentity(id: String, color: Int?, cells: Set<Int>) {
        val identity = AgentAvatarIdentity.identity(id)
        assertEquals("color for '$id'", color, identity.color)
        assertEquals("cells for '$id'", cells, identity.cells)
    }

    private fun pixels(icon: Icon): IntArray {
        val image = BufferedImage(icon.iconWidth, icon.iconHeight, BufferedImage.TYPE_INT_ARGB)
        val g = image.createGraphics()
        try {
            icon.paintIcon(null, g, 0, 0)
        } finally {
            g.dispose()
        }
        return image.getRGB(0, 0, image.width, image.height, null, 0, image.width)
    }
}
